title: DataWithVishal
description: Data Analytics and Data Scraping Blog
author: Vishal (Data Muggler)
avatar: /logo.png
email: webinspiration+18[at]gmail.com
skin: sunrise

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
#twitter:
#  username: ngzhio
#  card: summary
logo: logo.png
social:
  name: Vishal (Data Muggler)
  links:
 #   - https://twitter.com/ngzhio
 #   - https://www.facebook.com/ngzhio
    - https://github.com/datawithvishal
google_site_verification: 
lang: en
